//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryeTakip.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int Id { get; set; }
        public string HazirlanmaSuresi { get; set; }
        public string TeslimatSuresi { get; set; }
        public string KuryeIsim { get; set; }
        public string OdemeYontem { get; set; }
        public string RestoranIsim { get; set; }
        public string BolgeIsim { get; set; }
        public string Tarih { get; set; }
    }
}
